/**
 * Generates public/_redirects for Cloudflare Pages from:
 * 1. Posts with legacySlug set (exitwithella.io 301s)
 * 2. Redirects collection entries
 *
 * Run: pnpm generate-redirects
 * Runs automatically as part of pnpm build (prebuild hook).
 */
import 'dotenv/config'
import * as fs from 'node:fs'
import * as path from 'node:path'
import * as url from 'node:url'

import { getPayload } from 'payload'

import config from '../src/payload.config'

const __dirname = path.dirname(url.fileURLToPath(import.meta.url))
const OUTPUT = path.join(__dirname, '..', 'public', '_redirects')

async function generateRedirects() {
  const payload = await getPayload({ config })

  const lines: string[] = ['# Auto-generated by scripts/generate-redirects.ts — do not edit']

  // 1. Posts with legacySlug → new URL
  const postsResult = await payload.find({
    collection: 'posts',
    limit: 500,
    depth: 1,
    where: {
      legacySlug: { exists: true },
      status: { equals: 'published' },
    },
  })

  for (const post of postsResult.docs) {
    if (!post.legacySlug) continue
    const oldPath = `/blog/${post.legacySlug}`
    const newPath = `/blog/${post.slug}`
    if (oldPath !== newPath) {
      lines.push(`${oldPath} ${newPath} 301`)
    }
  }

  // 2. Redirects collection
  const redirectsResult = await payload.find({
    collection: 'redirects',
    limit: 500,
  })

  for (const redirect of redirectsResult.docs) {
    // Payload Redirects collection shape: from, to, statusCode
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const r = redirect as any
    if (r.from && r.to) {
      const code = r.statusCode ?? 301
      lines.push(`${r.from} ${r.to} ${code}`)
    }
  }

  fs.writeFileSync(OUTPUT, lines.join('\n') + '\n', 'utf8')
  console.log(`✓ Wrote ${lines.length - 1} redirect(s) to public/_redirects`)

  process.exit(0)
}

generateRedirects().catch((err) => {
  console.error(err)
  process.exit(1)
})
