/**
 * Seed script for ELLA — restores all CMS content from JSON dump files.
 *
 * Usage:  pnpm seed
 *
 * Reads from src/seed-data/*.json (generated by `pnpm dump`).
 * Creates or updates all collections and globals in order,
 * respecting relationship dependencies.
 *
 * Media file blobs are NOT handled here — only metadata records.
 * Actual files must be migrated to R2 separately.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import 'dotenv/config'
import type { Payload } from 'payload'
import { getPayload } from 'payload'

import config from './payload.config'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const dataDir = path.resolve(__dirname, 'seed-data')

// ── Helpers ──────────────────────────────────────────────────

function loadJSON<T = Record<string, unknown>[]>(filename: string): T {
  const filePath = path.join(dataDir, filename)
  if (!fs.existsSync(filePath)) {
    console.log(`  ⚠ ${filename} not found, skipping`)
    return [] as unknown as T
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'))
}

/**
 * Strip fields that Payload auto-generates or that cause validation issues
 * when creating/updating documents.
 */
function stripAutoFields(doc: Record<string, unknown>): Record<string, unknown> {
  const copy = { ...doc }
  delete copy.id
  delete copy.createdAt
  delete copy.updatedAt
  // Media: url and thumbnailURL are generated from filename by the storage adapter
  delete copy.url
  delete copy.thumbnailURL
  // Globals have these
  delete copy.globalType
  return copy
}

/**
 * Upsert a document: find by a unique field, create or update.
 * Returns the document ID (useful for relationship mapping).
 */
async function upsertDoc(
  payload: Payload,
  collection: string,
  doc: Record<string, unknown>,
  uniqueField: string,
): Promise<{ id: number; created: boolean }> {
  const uniqueValue = doc[uniqueField]
  const existing = await payload.find({
    collection: collection as any,
    where: { [uniqueField]: { equals: uniqueValue } },
    limit: 1,
    depth: 0,
  })

  const data = stripAutoFields(doc) as any

  if (existing.docs.length > 0) {
    const existingDoc = existing.docs[0] as any
    await payload.update({
      collection: collection as any,
      id: existingDoc.id,
      data,
    })
    return { id: existingDoc.id, created: false }
  }

  const created = await payload.create({
    collection: collection as any,
    data,
  })
  return { id: (created as any).id, created: true }
}

/**
 * Seed a collection from its JSON dump file.
 * Returns a map of original dump ID → new database ID for relationship fixup.
 */
async function seedCollection(
  payload: Payload,
  collection: string,
  uniqueField: string,
  options?: {
    /** Remap relationship fields using ID maps from previously seeded collections */
    remap?: Record<string, Map<number, number>>
  },
): Promise<Map<number, number>> {
  const filename = `${collection}.json`
  const docs = loadJSON<Record<string, unknown>[]>(filename)
  const idMap = new Map<number, number>()

  if (docs.length === 0) {
    console.log(`  ${collection}: empty`)
    return idMap
  }

  let created = 0
  let updated = 0

  for (const doc of docs) {
    const originalId = doc.id as number

    // Remap relationship IDs if needed
    if (options?.remap) {
      for (const [field, map] of Object.entries(options.remap)) {
        const value = doc[field]
        if (typeof value === 'number' && map.has(value)) {
          doc[field] = map.get(value)
        } else if (Array.isArray(value)) {
          doc[field] = value.map((v) => (typeof v === 'number' && map.has(v) ? map.get(v) : v))
        }
      }
    }

    const result = await upsertDoc(payload, collection, doc, uniqueField)
    idMap.set(originalId, result.id)
    if (result.created) created++
    else updated++
  }

  console.log(`  ✓ ${collection}: ${created} created, ${updated} updated`)
  return idMap
}

// ── Main ─────────────────────────────────────────────────────

async function seed() {
  console.log('Connecting to Payload...\n')
  const payload = await getPayload({ config })

  if (!fs.existsSync(dataDir)) {
    console.error(`Seed data directory not found: ${dataDir}`)
    console.error('Run "pnpm dump" first to generate seed data.')
    process.exit(1)
  }

  // ── 1. Independent collections (no foreign keys) ───────

  console.log('Independent collections:')

  const mediaMap = await seedCollection(payload, 'media', 'filename')
  const disciplineMap = await seedCollection(payload, 'disciplines', 'slug')
  const categoryMap = await seedCollection(payload, 'categories', 'slug')
  await seedCollection(payload, 'pricing-tiers', 'name')
  await seedCollection(payload, 'faq-items', 'question')
  await seedCollection(payload, 'redirects', 'from')
  await seedCollection(payload, 'vanguard-events', 'id')
  await seedCollection(payload, 'case-studies', 'id')

  // ── 2. Collections with relationships ──────────────────

  console.log('\nDependent collections:')

  await seedCollection(payload, 'partners', 'name', {
    remap: { logo: mediaMap },
  })
  const teamMemberMap = await seedCollection(payload, 'team-members', 'name', {
    remap: { photo: mediaMap },
  })
  await seedCollection(payload, 'testimonials', 'name', {
    remap: { photo: mediaMap },
  })
  await seedCollection(payload, 'tools', 'slug', {
    remap: { icon: mediaMap, disciplines: disciplineMap, pricingTier: mediaMap },
  })
  await seedCollection(payload, 'solutions', 'slug', {
    remap: { discipline: disciplineMap },
  })

  // ── 3. Content collections ─────────────────────────────
  // These have blocks with embedded media/testimonial/discipline references.
  // We need to deep-remap IDs within block arrays.

  console.log('\nContent collections:')

  const contentRemapFields = {
    // Top-level fields
    author: teamMemberMap,
    categories: categoryMap,
    disciplines: disciplineMap,
    featuredImage: mediaMap,
    relatedPosts: new Map<number, number>(), // posts reference other posts — handle after
    // Hero fields
    'hero.visual': mediaMap,
    'hero.backgroundImage': mediaMap,
    // Page background
    'pageBackground.image': mediaMap,
  }

  // Pages — deep remap media/testimonial refs in blocks
  const pagesData = loadJSON<Record<string, unknown>[]>('pages.json')
  for (const page of pagesData) {
    remapDeep(page, mediaMap, [
      'visual',
      'backgroundImage',
      'image',
      'icon',
      'screenshot',
      'coverImage',
      'media',
      'patternSvg',
    ])
    remapDeep(page, teamMemberMap, ['author'])
    remapDeep(page, disciplineMap, ['discipline', 'disciplines'])
    // Testimonial IDs reference the testimonials collection — but those IDs
    // haven't changed since we upsert by name. Still remap for safety.
    // testimonial fields in blocks reference testimonials collection by ID
  }

  let pagesCreated = 0
  let pagesUpdated = 0
  const pageMap = new Map<number, number>()

  for (const page of pagesData) {
    const originalId = page.id as number
    const result = await upsertDoc(payload, 'pages', page, 'slug')
    pageMap.set(originalId, result.id)
    if (result.created) pagesCreated++
    else pagesUpdated++
  }
  console.log(`  ✓ pages: ${pagesCreated} created, ${pagesUpdated} updated`)

  // Posts — remap author, categories, featuredImage, relatedPosts
  const postsData = loadJSON<Record<string, unknown>[]>('posts.json')
  const postMap = new Map<number, number>()

  // First pass: create/update all posts (without relatedPosts resolved)
  for (const post of postsData) {
    const originalId = post.id as number
    remapField(post, 'author', teamMemberMap)
    remapField(post, 'featuredImage', mediaMap)
    remapArrayField(post, 'categories', categoryMap)
    remapArrayField(post, 'disciplines', disciplineMap)
    // Clear relatedPosts for first pass — we'll set them after all posts exist
    const relatedPosts = post.relatedPosts
    post.relatedPosts = []

    const result = await upsertDoc(payload, 'posts', post, 'slug')
    postMap.set(originalId, result.id)

    // Restore for second pass
    post.relatedPosts = relatedPosts
  }

  // Second pass: update relatedPosts now that all post IDs are mapped
  for (const post of postsData) {
    if (Array.isArray(post.relatedPosts) && post.relatedPosts.length > 0) {
      const newId = postMap.get(post.id as number)
      const remapped = (post.relatedPosts as number[])
        .map((id) => postMap.get(id) ?? id)
        .filter(Boolean)
      if (newId && remapped.length > 0) {
        await payload.update({
          collection: 'posts',
          id: newId,
          data: { relatedPosts: remapped } as any,
        })
      }
    }
  }
  console.log(`  ✓ posts: ${postsData.length} processed (${postMap.size} mapped)`)

  // Landing pages
  const landingPagesData = loadJSON<Record<string, unknown>[]>('landing-pages.json')
  if (landingPagesData.length > 0) {
    for (const page of landingPagesData) {
      remapDeep(page, mediaMap, ['visual', 'backgroundImage', 'image', 'icon', 'media'])
    }
    for (const page of landingPagesData) {
      await upsertDoc(payload, 'landing-pages', page, 'slug')
    }
    console.log(`  ✓ landing-pages: ${landingPagesData.length} processed`)
  } else {
    console.log('  landing-pages: empty')
  }

  // ── 4. Globals ─────────────────────────────────────────

  console.log('\nGlobals:')
  const globalSlugs = ['site-settings', 'navigation', 'footer', 'pricing-page']

  for (const slug of globalSlugs) {
    const data = loadJSON<Record<string, unknown>>(`${slug}.json`)
    if (data && Object.keys(data).length > 0) {
      const cleaned = stripAutoFields(data)
      // Remap media references in globals
      remapDeep(cleaned, mediaMap, [
        'logo',
        'logomark',
        'ogImage',
        'backgroundImage',
        'footerLogo',
        'coverImage',
      ])
      await payload.updateGlobal({
        slug: slug as any,
        data: cleaned as any,
      })
      console.log(`  ✓ ${slug}`)
    } else {
      console.log(`  ${slug}: empty or not found`)
    }
  }

  console.log('\nSeed complete.')
  process.exit(0)
}

// ── Remap utilities ──────────────────────────────────────────

/** Remap a single relationship field (number → number) */
function remapField(
  obj: Record<string, unknown>,
  field: string,
  map: Map<number, number>,
) {
  if (field.includes('.')) {
    const [parent, child] = field.split('.')
    const nested = obj[parent]
    if (nested && typeof nested === 'object') {
      remapField(nested as Record<string, unknown>, child, map)
    }
    return
  }
  const value = obj[field]
  if (typeof value === 'number' && map.has(value)) {
    obj[field] = map.get(value)
  }
}

/** Remap an array of relationship IDs */
function remapArrayField(
  obj: Record<string, unknown>,
  field: string,
  map: Map<number, number>,
) {
  const value = obj[field]
  if (Array.isArray(value)) {
    obj[field] = value.map((v) => (typeof v === 'number' && map.has(v) ? map.get(v) : v))
  }
}

/**
 * Walk an object tree and remap any field whose key matches one of the
 * given field names, using the provided ID map. Handles nested objects
 * and arrays (like Payload blocks).
 */
function remapDeep(
  obj: unknown,
  map: Map<number, number>,
  fieldNames: string[],
) {
  if (obj === null || obj === undefined || typeof obj !== 'object') return

  if (Array.isArray(obj)) {
    for (const item of obj) {
      remapDeep(item, map, fieldNames)
    }
    return
  }

  const record = obj as Record<string, unknown>
  for (const [key, value] of Object.entries(record)) {
    if (fieldNames.includes(key)) {
      if (typeof value === 'number' && map.has(value)) {
        record[key] = map.get(value)
      } else if (Array.isArray(value)) {
        record[key] = value.map((v) =>
          typeof v === 'number' && map.has(v) ? map.get(v) : v,
        )
      }
    } else if (typeof value === 'object' && value !== null) {
      remapDeep(value, map, fieldNames)
    }
  }
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
